CREATE DATABASE  IF NOT EXISTS `serverdb`;
USE `serverdb`;


DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(32) ,
  `name` VARCHAR(16) ,
  `password` VARCHAR(32),
  `type` TINYINT UNSIGNED  CHECK(type IN(0,1)),
  `udeclare` VARCHAR(60) DEFAULT '个人说明。',  
  `ctime` TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
  
  PRIMARY KEY (`id`),
  UNIQUE KEY `email_UNIQUE` (`email`)
) AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;
/*type 0:专家 1:农民 */



CREATE TABLE `emails`(
	`email` VARCHAR(32),
	`code` VARCHAR(20),
	`type` TINYINT UNSIGNED  CHECK(type IN(0,1,2)),
	UNIQUE KEY (`email`,`type`)
)DEFAULT CHARSET=utf8;
/*type 0:注册 1:修改密码 2:忘记密码 */
/*
CREATE TABLE `messages`(
	`id` INT UNSIGNED NOT NULL ,
	`uid` INT UNSIGNED NOT NULL,
	`tid` INT UNSIGNED NOT NULL,
	`uname` VARCHAR(16),
	`utype` TINYINT UNSIGNED  CHECK(type IN(0,1)),
	`type` enum('TEXT','IMAGE','VOICE','TEL','VIDEO') DEFAULT NULL,
	`content` VARCHAR(256) DEFAULT NULL,
	`ctime` TIMESTAMP ,
	INDEX (`tid`)
)DEFAULT CHARSET=utf8;
*/
CREATE TABLE `unreadmessages`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`uid` INT UNSIGNED NOT NULL,
	`tid` INT UNSIGNED NOT NULL,
	`uname` VARCHAR(16),
	`utype` TINYINT UNSIGNED  CHECK(type IN(0,1)),
	`type` enum('TEXT','IMAGE','VOICE','TEL','VIDEO') DEFAULT NULL,
	`content` VARCHAR(526) DEFAULT NULL,
	`ctime` TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	INDEX (`tid`)
)AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
/*
CREATE TABLE `online`(
	`uid` INT UNSIGNED NOT NULL,
	`uname` VARCHAR(16),
	`type` TINYINT UNSIGNED  CHECK(type IN(0,1)),
	`ltime` TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
	UNIQUE KEY  (`uid`)
)DEFAULT CHARSET=utf8;

CREATE TABLE `groups`(
	`id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(30),
	PRIMARY KEY (`id`)
)AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `group_messages`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`gid` TINYINT UNSIGNED NOT NULL,
	`uid` INT UNSIGNED NOT NULL,
	`uname` VARCHAR(16),
	`utype` TINYINT UNSIGNED  CHECK(type IN(0,1)),
	`type` enum('TEXT','IMAGE','VOICE') DEFAULT NULL,
	`content` VARCHAR(256) DEFAULT NULL,
	`ctime` TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	INDEX (`gid`)
)AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
*/


